[files]
exclude = [
    "src/core/build*",
    "src/core/build*/*",
    "*/_deps/*",
    "*_deps*",
    "prototype/*",
    "*.egg-info/*",
    "__pycache__/*",
    "todo/*",
    "paper/*",
    "dev_notes/*",
]
