# Generated by Rcpp::compileAttributes() - do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Compute band accuracy metric
#'
#' @param pred Numeric vector of predictions
#' @param target Numeric vector of targets
#' @param threshold Threshold for band (default 0.25)
#'
#' @return Band accuracy as double
#'
#' @export
resolve_band_accuracy <- function(pred, target, threshold = 0.25) {
    .Call(`_resolve_resolve_band_accuracy`, pred, target, threshold)
}

#' Compute mean absolute error
#'
#' @param pred Numeric vector of predictions
#' @param target Numeric vector of targets
#'
#' @return MAE as double
#'
#' @export
resolve_mae <- function(pred, target) {
    .Call(`_resolve_resolve_mae`, pred, target)
}

#' Compute root mean squared error
#'
#' @param pred Numeric vector of predictions
#' @param target Numeric vector of targets
#'
#' @return RMSE as double
#'
#' @export
resolve_rmse <- function(pred, target) {
    .Call(`_resolve_resolve_rmse`, pred, target)
}

#' Compute symmetric mean absolute percentage error
#'
#' @param pred Numeric vector of predictions
#' @param target Numeric vector of targets
#' @param eps Small epsilon to avoid division by zero (default 1e-8)
#'
#' @return sMAPE as double
#'
#' @export
resolve_smape <- function(pred, target, eps = 1e-8) {
    .Call(`_resolve_resolve_smape`, pred, target, eps)
}

#' Compute classification accuracy
#'
#' @param pred Numeric vector of predictions (class labels)
#' @param target Numeric vector of targets (class labels)
#'
#' @return Accuracy as double
#'
#' @export
resolve_accuracy <- function(pred, target) {
    .Call(`_resolve_resolve_accuracy`, pred, target)
}

# Load the Rcpp module for resolve
loadModule("resolve_module", TRUE)
