# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

resolve_band_accuracy <- function(pred, target, threshold = 0.25) {
    .Call(`_resolve_resolve_band_accuracy`, pred, target, threshold)
}

resolve_mae <- function(pred, target) {
    .Call(`_resolve_resolve_mae`, pred, target)
}

resolve_rmse <- function(pred, target) {
    .Call(`_resolve_resolve_rmse`, pred, target)
}

resolve_smape <- function(pred, target, eps = 1e-8) {
    .Call(`_resolve_resolve_smape`, pred, target, eps)
}

resolve_accuracy <- function(pred, target) {
    .Call(`_resolve_resolve_accuracy`, pred, target)
}

resolve_r_squared <- function(pred, target) {
    .Call(`_resolve_resolve_r_squared`, pred, target)
}

resolve_version <- function() {
    .Call(`_resolve_resolve_version`)
}

resolve_set_vram_fraction <- function(fraction, device_index = -1L) {
    invisible(.Call(`_resolve_resolve_set_vram_fraction`, fraction, device_index))
}

