// Generated by Rcpp::compileAttributes() - edits will be overwritten

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// resolve_band_accuracy
double resolve_band_accuracy(NumericVector pred, NumericVector target, double threshold);
RcppExport SEXP _resolve_resolve_band_accuracy(SEXP predSEXP, SEXP targetSEXP, SEXP thresholdSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type pred(predSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type target(targetSEXP);
    Rcpp::traits::input_parameter< double >::type threshold(thresholdSEXP);
    rcpp_result_gen = Rcpp::wrap(resolve_band_accuracy(pred, target, threshold));
    return rcpp_result_gen;
END_RCPP
}

// resolve_mae
double resolve_mae(NumericVector pred, NumericVector target);
RcppExport SEXP _resolve_resolve_mae(SEXP predSEXP, SEXP targetSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type pred(predSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type target(targetSEXP);
    rcpp_result_gen = Rcpp::wrap(resolve_mae(pred, target));
    return rcpp_result_gen;
END_RCPP
}

// resolve_rmse
double resolve_rmse(NumericVector pred, NumericVector target);
RcppExport SEXP _resolve_resolve_rmse(SEXP predSEXP, SEXP targetSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type pred(predSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type target(targetSEXP);
    rcpp_result_gen = Rcpp::wrap(resolve_rmse(pred, target));
    return rcpp_result_gen;
END_RCPP
}

// resolve_smape
double resolve_smape(NumericVector pred, NumericVector target, double eps);
RcppExport SEXP _resolve_resolve_smape(SEXP predSEXP, SEXP targetSEXP, SEXP epsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type pred(predSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type target(targetSEXP);
    Rcpp::traits::input_parameter< double >::type eps(epsSEXP);
    rcpp_result_gen = Rcpp::wrap(resolve_smape(pred, target, eps));
    return rcpp_result_gen;
END_RCPP
}

// resolve_model_new
SEXP resolve_model_new(List schema_list, List config_list);
RcppExport SEXP _resolve_resolve_model_new(SEXP schema_listSEXP, SEXP config_listSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List >::type schema_list(schema_listSEXP);
    Rcpp::traits::input_parameter< List >::type config_list(config_listSEXP);
    rcpp_result_gen = Rcpp::wrap(resolve_model_new(schema_list, config_list));
    return rcpp_result_gen;
END_RCPP
}

// resolve_model_forward
List resolve_model_forward(SEXP model_ptr, NumericMatrix continuous, Nullable<IntegerMatrix> genus_ids, Nullable<IntegerMatrix> family_ids);
RcppExport SEXP _resolve_resolve_model_forward(SEXP model_ptrSEXP, SEXP continuousSEXP, SEXP genus_idsSEXP, SEXP family_idsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type model_ptr(model_ptrSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type continuous(continuousSEXP);
    Rcpp::traits::input_parameter< Nullable<IntegerMatrix> >::type genus_ids(genus_idsSEXP);
    Rcpp::traits::input_parameter< Nullable<IntegerMatrix> >::type family_ids(family_idsSEXP);
    rcpp_result_gen = Rcpp::wrap(resolve_model_forward(model_ptr, continuous, genus_ids, family_ids));
    return rcpp_result_gen;
END_RCPP
}

// resolve_model_get_latent
NumericMatrix resolve_model_get_latent(SEXP model_ptr, NumericMatrix continuous, Nullable<IntegerMatrix> genus_ids, Nullable<IntegerMatrix> family_ids);
RcppExport SEXP _resolve_resolve_model_get_latent(SEXP model_ptrSEXP, SEXP continuousSEXP, SEXP genus_idsSEXP, SEXP family_idsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type model_ptr(model_ptrSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type continuous(continuousSEXP);
    Rcpp::traits::input_parameter< Nullable<IntegerMatrix> >::type genus_ids(genus_idsSEXP);
    Rcpp::traits::input_parameter< Nullable<IntegerMatrix> >::type family_ids(family_idsSEXP);
    rcpp_result_gen = Rcpp::wrap(resolve_model_get_latent(model_ptr, continuous, genus_ids, family_ids));
    return rcpp_result_gen;
END_RCPP
}

// resolve_trainer_new
SEXP resolve_trainer_new(SEXP model_ptr, List config_list);
RcppExport SEXP _resolve_resolve_trainer_new(SEXP model_ptrSEXP, SEXP config_listSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type model_ptr(model_ptrSEXP);
    Rcpp::traits::input_parameter< List >::type config_list(config_listSEXP);
    rcpp_result_gen = Rcpp::wrap(resolve_trainer_new(model_ptr, config_list));
    return rcpp_result_gen;
END_RCPP
}

// resolve_trainer_prepare_data
void resolve_trainer_prepare_data(SEXP trainer_ptr, NumericMatrix continuous, List targets_list, Nullable<IntegerMatrix> genus_ids, Nullable<IntegerMatrix> family_ids, double test_size, int seed);
RcppExport SEXP _resolve_resolve_trainer_prepare_data(SEXP trainer_ptrSEXP, SEXP continuousSEXP, SEXP targets_listSEXP, SEXP genus_idsSEXP, SEXP family_idsSEXP, SEXP test_sizeSEXP, SEXP seedSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type trainer_ptr(trainer_ptrSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type continuous(continuousSEXP);
    Rcpp::traits::input_parameter< List >::type targets_list(targets_listSEXP);
    Rcpp::traits::input_parameter< Nullable<IntegerMatrix> >::type genus_ids(genus_idsSEXP);
    Rcpp::traits::input_parameter< Nullable<IntegerMatrix> >::type family_ids(family_idsSEXP);
    Rcpp::traits::input_parameter< double >::type test_size(test_sizeSEXP);
    Rcpp::traits::input_parameter< int >::type seed(seedSEXP);
    resolve_trainer_prepare_data(trainer_ptr, continuous, targets_list, genus_ids, family_ids, test_size, seed);
    return R_NilValue;
END_RCPP
}

// resolve_trainer_fit
List resolve_trainer_fit(SEXP trainer_ptr);
RcppExport SEXP _resolve_resolve_trainer_fit(SEXP trainer_ptrSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type trainer_ptr(trainer_ptrSEXP);
    rcpp_result_gen = Rcpp::wrap(resolve_trainer_fit(trainer_ptr));
    return rcpp_result_gen;
END_RCPP
}

// resolve_trainer_save
void resolve_trainer_save(SEXP trainer_ptr, std::string path);
RcppExport SEXP _resolve_resolve_trainer_save(SEXP trainer_ptrSEXP, SEXP pathSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type trainer_ptr(trainer_ptrSEXP);
    Rcpp::traits::input_parameter< std::string >::type path(pathSEXP);
    resolve_trainer_save(trainer_ptr, path);
    return R_NilValue;
END_RCPP
}

// resolve_trainer_load
List resolve_trainer_load(std::string path);
RcppExport SEXP _resolve_resolve_trainer_load(SEXP pathSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::string >::type path(pathSEXP);
    rcpp_result_gen = Rcpp::wrap(resolve_trainer_load(path));
    return rcpp_result_gen;
END_RCPP
}

// resolve_predictor_new
SEXP resolve_predictor_new(SEXP model_ptr, SEXP scalers_ptr);
RcppExport SEXP _resolve_resolve_predictor_new(SEXP model_ptrSEXP, SEXP scalers_ptrSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type model_ptr(model_ptrSEXP);
    Rcpp::traits::input_parameter< SEXP >::type scalers_ptr(scalers_ptrSEXP);
    rcpp_result_gen = Rcpp::wrap(resolve_predictor_new(model_ptr, scalers_ptr));
    return rcpp_result_gen;
END_RCPP
}

// resolve_predictor_load
SEXP resolve_predictor_load(std::string path);
RcppExport SEXP _resolve_resolve_predictor_load(SEXP pathSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::string >::type path(pathSEXP);
    rcpp_result_gen = Rcpp::wrap(resolve_predictor_load(path));
    return rcpp_result_gen;
END_RCPP
}

// resolve_predictor_predict
List resolve_predictor_predict(SEXP predictor_ptr, NumericMatrix continuous, Nullable<IntegerMatrix> genus_ids, Nullable<IntegerMatrix> family_ids, bool return_latent);
RcppExport SEXP _resolve_resolve_predictor_predict(SEXP predictor_ptrSEXP, SEXP continuousSEXP, SEXP genus_idsSEXP, SEXP family_idsSEXP, SEXP return_latentSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type predictor_ptr(predictor_ptrSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type continuous(continuousSEXP);
    Rcpp::traits::input_parameter< Nullable<IntegerMatrix> >::type genus_ids(genus_idsSEXP);
    Rcpp::traits::input_parameter< Nullable<IntegerMatrix> >::type family_ids(family_idsSEXP);
    Rcpp::traits::input_parameter< bool >::type return_latent(return_latentSEXP);
    rcpp_result_gen = Rcpp::wrap(resolve_predictor_predict(predictor_ptr, continuous, genus_ids, family_ids, return_latent));
    return rcpp_result_gen;
END_RCPP
}

// resolve_predictor_get_embeddings
NumericMatrix resolve_predictor_get_embeddings(SEXP predictor_ptr, NumericMatrix continuous, Nullable<IntegerMatrix> genus_ids, Nullable<IntegerMatrix> family_ids);
RcppExport SEXP _resolve_resolve_predictor_get_embeddings(SEXP predictor_ptrSEXP, SEXP continuousSEXP, SEXP genus_idsSEXP, SEXP family_idsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type predictor_ptr(predictor_ptrSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type continuous(continuousSEXP);
    Rcpp::traits::input_parameter< Nullable<IntegerMatrix> >::type genus_ids(genus_idsSEXP);
    Rcpp::traits::input_parameter< Nullable<IntegerMatrix> >::type family_ids(family_idsSEXP);
    rcpp_result_gen = Rcpp::wrap(resolve_predictor_get_embeddings(predictor_ptr, continuous, genus_ids, family_ids));
    return rcpp_result_gen;
END_RCPP
}

// resolve_predictor_get_genus_embeddings
NumericMatrix resolve_predictor_get_genus_embeddings(SEXP predictor_ptr);
RcppExport SEXP _resolve_resolve_predictor_get_genus_embeddings(SEXP predictor_ptrSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type predictor_ptr(predictor_ptrSEXP);
    rcpp_result_gen = Rcpp::wrap(resolve_predictor_get_genus_embeddings(predictor_ptr));
    return rcpp_result_gen;
END_RCPP
}

// resolve_predictor_get_family_embeddings
NumericMatrix resolve_predictor_get_family_embeddings(SEXP predictor_ptr);
RcppExport SEXP _resolve_resolve_predictor_get_family_embeddings(SEXP predictor_ptrSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type predictor_ptr(predictor_ptrSEXP);
    rcpp_result_gen = Rcpp::wrap(resolve_predictor_get_family_embeddings(predictor_ptr));
    return rcpp_result_gen;
END_RCPP
}

// resolve_cuda_available
bool resolve_cuda_available();
RcppExport SEXP _resolve_resolve_cuda_available() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_result_gen = Rcpp::wrap(resolve_cuda_available());
    return rcpp_result_gen;
END_RCPP
}

// resolve_cuda_device_count
int resolve_cuda_device_count();
RcppExport SEXP _resolve_resolve_cuda_device_count() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_result_gen = Rcpp::wrap(resolve_cuda_device_count());
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_resolve_resolve_band_accuracy", (DL_FUNC) &_resolve_resolve_band_accuracy, 3},
    {"_resolve_resolve_mae", (DL_FUNC) &_resolve_resolve_mae, 2},
    {"_resolve_resolve_rmse", (DL_FUNC) &_resolve_resolve_rmse, 2},
    {"_resolve_resolve_smape", (DL_FUNC) &_resolve_resolve_smape, 3},
    {"_resolve_resolve_model_new", (DL_FUNC) &_resolve_resolve_model_new, 2},
    {"_resolve_resolve_model_forward", (DL_FUNC) &_resolve_resolve_model_forward, 4},
    {"_resolve_resolve_model_get_latent", (DL_FUNC) &_resolve_resolve_model_get_latent, 4},
    {"_resolve_resolve_trainer_new", (DL_FUNC) &_resolve_resolve_trainer_new, 2},
    {"_resolve_resolve_trainer_prepare_data", (DL_FUNC) &_resolve_resolve_trainer_prepare_data, 7},
    {"_resolve_resolve_trainer_fit", (DL_FUNC) &_resolve_resolve_trainer_fit, 1},
    {"_resolve_resolve_trainer_save", (DL_FUNC) &_resolve_resolve_trainer_save, 2},
    {"_resolve_resolve_trainer_load", (DL_FUNC) &_resolve_resolve_trainer_load, 1},
    {"_resolve_resolve_predictor_new", (DL_FUNC) &_resolve_resolve_predictor_new, 2},
    {"_resolve_resolve_predictor_load", (DL_FUNC) &_resolve_resolve_predictor_load, 1},
    {"_resolve_resolve_predictor_predict", (DL_FUNC) &_resolve_resolve_predictor_predict, 5},
    {"_resolve_resolve_predictor_get_embeddings", (DL_FUNC) &_resolve_resolve_predictor_get_embeddings, 4},
    {"_resolve_resolve_predictor_get_genus_embeddings", (DL_FUNC) &_resolve_resolve_predictor_get_genus_embeddings, 1},
    {"_resolve_resolve_predictor_get_family_embeddings", (DL_FUNC) &_resolve_resolve_predictor_get_family_embeddings, 1},
    {"_resolve_resolve_cuda_available", (DL_FUNC) &_resolve_resolve_cuda_available, 0},
    {"_resolve_resolve_cuda_device_count", (DL_FUNC) &_resolve_resolve_cuda_device_count, 0},
    {NULL, NULL, 0}
};

RcppExport void R_init_resolve(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
