// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// resolve_band_accuracy
double resolve_band_accuracy(NumericVector pred, NumericVector target, double threshold);
RcppExport SEXP _resolve_resolve_band_accuracy(SEXP predSEXP, SEXP targetSEXP, SEXP thresholdSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type pred(predSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type target(targetSEXP);
    Rcpp::traits::input_parameter< double >::type threshold(thresholdSEXP);
    rcpp_result_gen = Rcpp::wrap(resolve_band_accuracy(pred, target, threshold));
    return rcpp_result_gen;
END_RCPP
}
// resolve_mae
double resolve_mae(NumericVector pred, NumericVector target);
RcppExport SEXP _resolve_resolve_mae(SEXP predSEXP, SEXP targetSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type pred(predSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type target(targetSEXP);
    rcpp_result_gen = Rcpp::wrap(resolve_mae(pred, target));
    return rcpp_result_gen;
END_RCPP
}
// resolve_rmse
double resolve_rmse(NumericVector pred, NumericVector target);
RcppExport SEXP _resolve_resolve_rmse(SEXP predSEXP, SEXP targetSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type pred(predSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type target(targetSEXP);
    rcpp_result_gen = Rcpp::wrap(resolve_rmse(pred, target));
    return rcpp_result_gen;
END_RCPP
}
// resolve_smape
double resolve_smape(NumericVector pred, NumericVector target, double eps);
RcppExport SEXP _resolve_resolve_smape(SEXP predSEXP, SEXP targetSEXP, SEXP epsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type pred(predSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type target(targetSEXP);
    Rcpp::traits::input_parameter< double >::type eps(epsSEXP);
    rcpp_result_gen = Rcpp::wrap(resolve_smape(pred, target, eps));
    return rcpp_result_gen;
END_RCPP
}
// resolve_accuracy
double resolve_accuracy(NumericVector pred, NumericVector target);
RcppExport SEXP _resolve_resolve_accuracy(SEXP predSEXP, SEXP targetSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type pred(predSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type target(targetSEXP);
    rcpp_result_gen = Rcpp::wrap(resolve_accuracy(pred, target));
    return rcpp_result_gen;
END_RCPP
}
// resolve_r_squared
double resolve_r_squared(NumericVector pred, NumericVector target);
RcppExport SEXP _resolve_resolve_r_squared(SEXP predSEXP, SEXP targetSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type pred(predSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type target(targetSEXP);
    rcpp_result_gen = Rcpp::wrap(resolve_r_squared(pred, target));
    return rcpp_result_gen;
END_RCPP
}
// resolve_version
std::string resolve_version();
RcppExport SEXP _resolve_resolve_version() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_result_gen = Rcpp::wrap(resolve_version());
    return rcpp_result_gen;
END_RCPP
}
// resolve_set_vram_fraction
void resolve_set_vram_fraction(double fraction, int device_index);
RcppExport SEXP _resolve_resolve_set_vram_fraction(SEXP fractionSEXP, SEXP device_indexSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type fraction(fractionSEXP);
    Rcpp::traits::input_parameter< int >::type device_index(device_indexSEXP);
    resolve_set_vram_fraction(fraction, device_index);
    return R_NilValue;
END_RCPP
}
// resolve_set_thread_pools
void resolve_set_thread_pools(int intraop_threads, int interop_threads);
RcppExport SEXP _resolve_resolve_set_thread_pools(SEXP intraop_threadsSEXP, SEXP interop_threadsSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type intraop_threads(intraop_threadsSEXP);
    Rcpp::traits::input_parameter< int >::type interop_threads(interop_threadsSEXP);
    resolve_set_thread_pools(intraop_threads, interop_threads);
    return R_NilValue;
END_RCPP
}
// resolve_install_crash_handler
void resolve_install_crash_handler(int shutdown_exit_code);
RcppExport SEXP _resolve_resolve_install_crash_handler(SEXP shutdown_exit_codeSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type shutdown_exit_code(shutdown_exit_codeSEXP);
    resolve_install_crash_handler(shutdown_exit_code);
    return R_NilValue;
END_RCPP
}
// resolve_signal_work_complete
void resolve_signal_work_complete();
RcppExport SEXP _resolve_resolve_signal_work_complete() {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    resolve_signal_work_complete();
    return R_NilValue;
END_RCPP
}
// resolve_configure_cuda_allocator
std::string resolve_configure_cuda_allocator(bool force);
RcppExport SEXP _resolve_resolve_configure_cuda_allocator(SEXP forceSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< bool >::type force(forceSEXP);
    rcpp_result_gen = Rcpp::wrap(resolve_configure_cuda_allocator(force));
    return rcpp_result_gen;
END_RCPP
}
// resolve_capi_load_lib
bool resolve_capi_load_lib(std::string path);
RcppExport SEXP _resolve_resolve_capi_load_lib(SEXP pathSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::string >::type path(pathSEXP);
    rcpp_result_gen = Rcpp::wrap(resolve_capi_load_lib(path));
    return rcpp_result_gen;
END_RCPP
}
// resolve_capi_is_available
bool resolve_capi_is_available();
RcppExport SEXP _resolve_resolve_capi_is_available() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_result_gen = Rcpp::wrap(resolve_capi_is_available());
    return rcpp_result_gen;
END_RCPP
}
// resolve_capi_load_error
std::string resolve_capi_load_error();
RcppExport SEXP _resolve_resolve_capi_load_error() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_result_gen = Rcpp::wrap(resolve_capi_load_error());
    return rcpp_result_gen;
END_RCPP
}

RcppExport SEXP _rcpp_module_boot_resolve_module();

static const R_CallMethodDef CallEntries[] = {
    {"_resolve_resolve_band_accuracy", (DL_FUNC) &_resolve_resolve_band_accuracy, 3},
    {"_resolve_resolve_mae", (DL_FUNC) &_resolve_resolve_mae, 2},
    {"_resolve_resolve_rmse", (DL_FUNC) &_resolve_resolve_rmse, 2},
    {"_resolve_resolve_smape", (DL_FUNC) &_resolve_resolve_smape, 3},
    {"_resolve_resolve_accuracy", (DL_FUNC) &_resolve_resolve_accuracy, 2},
    {"_resolve_resolve_r_squared", (DL_FUNC) &_resolve_resolve_r_squared, 2},
    {"_resolve_resolve_version", (DL_FUNC) &_resolve_resolve_version, 0},
    {"_resolve_resolve_set_vram_fraction", (DL_FUNC) &_resolve_resolve_set_vram_fraction, 2},
    {"_resolve_resolve_set_thread_pools", (DL_FUNC) &_resolve_resolve_set_thread_pools, 2},
    {"_resolve_resolve_install_crash_handler", (DL_FUNC) &_resolve_resolve_install_crash_handler, 1},
    {"_resolve_resolve_signal_work_complete", (DL_FUNC) &_resolve_resolve_signal_work_complete, 0},
    {"_resolve_resolve_configure_cuda_allocator", (DL_FUNC) &_resolve_resolve_configure_cuda_allocator, 1},
    {"_resolve_resolve_capi_load_lib", (DL_FUNC) &_resolve_resolve_capi_load_lib, 1},
    {"_resolve_resolve_capi_is_available", (DL_FUNC) &_resolve_resolve_capi_is_available, 0},
    {"_resolve_resolve_capi_load_error", (DL_FUNC) &_resolve_resolve_capi_load_error, 0},
    {"_rcpp_module_boot_resolve_module", (DL_FUNC) &_rcpp_module_boot_resolve_module, 0},
    {NULL, NULL, 0}
};

RcppExport void R_init_resolve(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
