// Generated by Rcpp::compileAttributes() - do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// resolve_band_accuracy
double resolve_band_accuracy(NumericVector pred, NumericVector target, double threshold);
RcppExport SEXP _resolve_resolve_band_accuracy(SEXP predSEXP, SEXP targetSEXP, SEXP thresholdSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type pred(predSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type target(targetSEXP);
    Rcpp::traits::input_parameter< double >::type threshold(thresholdSEXP);
    rcpp_result_gen = Rcpp::wrap(resolve_band_accuracy(pred, target, threshold));
    return rcpp_result_gen;
END_RCPP
}
// resolve_mae
double resolve_mae(NumericVector pred, NumericVector target);
RcppExport SEXP _resolve_resolve_mae(SEXP predSEXP, SEXP targetSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type pred(predSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type target(targetSEXP);
    rcpp_result_gen = Rcpp::wrap(resolve_mae(pred, target));
    return rcpp_result_gen;
END_RCPP
}
// resolve_rmse
double resolve_rmse(NumericVector pred, NumericVector target);
RcppExport SEXP _resolve_resolve_rmse(SEXP predSEXP, SEXP targetSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type pred(predSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type target(targetSEXP);
    rcpp_result_gen = Rcpp::wrap(resolve_rmse(pred, target));
    return rcpp_result_gen;
END_RCPP
}
// resolve_smape
double resolve_smape(NumericVector pred, NumericVector target, double eps);
RcppExport SEXP _resolve_resolve_smape(SEXP predSEXP, SEXP targetSEXP, SEXP epsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type pred(predSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type target(targetSEXP);
    Rcpp::traits::input_parameter< double >::type eps(epsSEXP);
    rcpp_result_gen = Rcpp::wrap(resolve_smape(pred, target, eps));
    return rcpp_result_gen;
END_RCPP
}
// resolve_accuracy
double resolve_accuracy(NumericVector pred, NumericVector target);
RcppExport SEXP _resolve_resolve_accuracy(SEXP predSEXP, SEXP targetSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type pred(predSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type target(targetSEXP);
    rcpp_result_gen = Rcpp::wrap(resolve_accuracy(pred, target));
    return rcpp_result_gen;
END_RCPP
}
// resolve_version
std::string resolve_version();
RcppExport SEXP _resolve_resolve_version() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_result_gen = Rcpp::wrap(resolve_version());
    return rcpp_result_gen;
END_RCPP
}

RcppExport SEXP _rcpp_module_boot_resolve_module(void);

static const R_CallMethodDef CallEntries[] = {
    {"_resolve_resolve_band_accuracy", (DL_FUNC) &_resolve_resolve_band_accuracy, 3},
    {"_resolve_resolve_mae", (DL_FUNC) &_resolve_resolve_mae, 2},
    {"_resolve_resolve_rmse", (DL_FUNC) &_resolve_resolve_rmse, 2},
    {"_resolve_resolve_smape", (DL_FUNC) &_resolve_resolve_smape, 3},
    {"_resolve_resolve_accuracy", (DL_FUNC) &_resolve_resolve_accuracy, 2},
    {"_resolve_resolve_version", (DL_FUNC) &_resolve_resolve_version, 0},
    {"_rcpp_module_boot_resolve_module", (DL_FUNC) &_rcpp_module_boot_resolve_module, 0},
    {NULL, NULL, 0}
};

RcppExport void R_init_resolve(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
